import { readdir, readFile, mkdir } from 'fs/promises';
import { join, relative, extname, dirname } from 'path';

const PUBLIC_DIR = join(import.meta.dir, '..', 'public');
const OUTPUT_FILE = join(import.meta.dir, '..', 'src', 'generated', 'static-assets.ts');

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html',
  '.htm': 'text/html',
  '.js': 'application/javascript',
  '.mjs': 'application/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.ico': 'image/x-icon',
  '.woff2': 'font/woff2',
  '.woff': 'font/woff',
  '.ttf': 'font/ttf',
  '.otf': 'font/otf',
  '.webp': 'image/webp',
};

async function scanDir(dir: string, files: { path: string; content: string }[] = []) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      // 跳过 logs 目录（运行时生成的日志，不是静态资源）
      if (entry.name === 'logs') continue;
      await scanDir(fullPath, files);
    } else {
      const relPath = '/' + relative(PUBLIC_DIR, fullPath).replace(/\\/g, '/');
      const content = await readFile(fullPath, 'utf-8');
      files.push({ path: relPath, content });
    }
  }
  return files;
}

const files = await scanDir(PUBLIC_DIR);
const lines: string[] = [];
lines.push('// Auto-generated by scripts/build-assets.ts');
lines.push('// Do not edit manually');
lines.push('');
lines.push('export const STATIC_ASSETS: Record<string, { content: string; contentType: string }> = {');

for (const file of files) {
  const ext = extname(file.path);
  const mime = MIME_TYPES[ext] || 'application/octet-stream';
  const escaped = file.content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');
  lines.push(`  '${file.path}': {`);
  lines.push(`    content: \`${escaped}\`,`);
  lines.push(`    contentType: '${mime}',`);
  lines.push(`  },`);
}

lines.push('};');
lines.push('');
lines.push(`// Total assets: ${files.length}`);
lines.push('');

// 确保目录存在
await mkdir(dirname(OUTPUT_FILE), { recursive: true });
await Bun.write(OUTPUT_FILE, lines.join('\n'));

console.log(`Generated static-assets.ts with ${files.length} assets`);
